spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


greeting:
  message: Hello default profile

---

spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: Hello prod profile

---

spring:
  config:
    activate:
      on-profile: test
greeting:
  message: Hello test profile


