spring:
  application:
    name: catalog-service
greeting:
  message: Hello default profile

---

spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: Hello prod profile

---

spring:
  config:
    activate:
      on-profile: test
greeting:
  message: Hello test profile


